name: sd
channels:
  - pytorch
  - nvidia
  - defaults
dependencies:
  - pip
  - python
  - pytorch 
  - torchvision
  - pytorch-cuda=11.8
  - pip:
      - anyio
      - click
      - compel
      - diffusers
      - fastapi
      - h11
      - huey
      - idna
      - opencv-python
      - psutil
      - pydantic
      - pymemcache
      - requests
      - sniffio
      - starlette
      - uvicorn
      - accelerate
      - invisible_watermark
      - transformers
      - "pysimplegui<5.0.0"