name: sd
channels:
  - pytorch
  - defaults
dependencies:
  - pip
  - python
  - pytorch::pytorch 
  - torchvision
  - pip:
      - anyio
      - click
      - compel
      - diffusers==0.21.2
      - fastapi
      - h11
      - huey
      - idna
      - opencv-python
      - psutil
      - pydantic
      - requests
      - sniffio
      - starlette
      - uvicorn
      - accelerate
      - invisible_watermark
      - transformers